### ISSUE TITLE
Project TODO

### ISSUE THREAD

**Issue by zougui1** [zougui1/dynamic-redux#1]
- [ ] pass to second argument of the first function of middlewares the current state
- [ ]  pass to third argument of the first function of middlewares the actions of current state
- [ ]  proper error handling for `Query`
- [ ] automated unit testing
- [ ] improve `Query`'s typing in TS
- [ ] the user can create its own action
- [ ] add `byKind` and `byProperty` methods to `QueryDispatch`
